### ISSUE TITLE
[gatsby-remark-images-insert-wrapper-attributes] aligh=left doesn't work

### ISSUE THREAD

**Issue by challengy1** [newsproutsmedia/gatsby-remark-images-insert-wrapper-attributes#6]
Gatsby-config.js is as follows:
```
{
      resolve: `gatsby-transformer-remark`,
      options: {
        // Footnotes mode (default: true)
        footnotes: true,
        // GitHub Flavored Markdown mode (default: true)
        gfm: true,
        // Plugins configs
        plugins: [
          `gatsby-remark-katex`,
          `gatsby-remark-autolink-headers`,
          {
            resolve: `gatsby-remark-extract-image-attributes`,
            options: {
              properties: ['align'],
            },
          },
          `gatsby-remark-images`,
          `gatsby-remark-images-insert-wrapper-attributes`,
        ],
      },
```
In the markdown file, I specified as follows:
```
![CAT](cat.jpg?align=left)
```

I expected the photo is located at the most lefthand side of the window. However, it didn't work.

As I examine the CSS with Crome development helper, I found that the margin-left:auto and margin-right:auto. I assume this was the reason why.

<img width="506" alt="スクリーンショット 2021-06-28 11 46 26" src="https://user-images.githubusercontent.com/22554597/123572538-5a857b00-d807-11eb-8003-eb01a69fada2.png">

I would appreciate it if you could let me know how to resolve this case. I want to put some pictures on the left side of the browser. I confirmed that the size of the picture was successfully changed.
The issue I face now is only alignment.

BR, KI (in Japan)

**Comment by newsproutsmedia** [comment]
Hi there!

Have you added CSS to float the image? If not, try adding the following to your global.css file:

```
// CSS classes to align image on screens larger than 640px

@media only screen and (min-width:641px) {

  [data-align="right"] {
      float: right;
      margin: 6px 0 10px 40px !important;
  }

  [data-align="left"] {
      float: left;
      margin: 6px 40px 10px 0 !important;
  }

  figure[data-align] {
      margin-bottom: 60px !important;
  }

// CSS classes to remove width and height on screens below 640px in width

@media only screen and (max-width:640px) {

  .gatsby-resp-image-wrapper {
      width: unset !important;
      height: unset !important;
  }

  .gatsby-resp-image-figure {
      width: unset !important;
      height: unset !important;
  }

}
```
Also, you can remove the options from the gatsby-remark-extract-image-attributes plugin. It extracts "align" by default. So your gatsby.config would be: 
```
{
      resolve: `gatsby-transformer-remark`,
      options: {
        // Footnotes mode (default: true)
        footnotes: true,
        // GitHub Flavored Markdown mode (default: true)
        gfm: true,
        // Plugins configs
        plugins: [
          `gatsby-remark-katex`,
          `gatsby-remark-autolink-headers`,
          `gatsby-remark-extract-image-attributes`,
          `gatsby-remark-images`,
          `gatsby-remark-images-insert-wrapper-attributes`,
        ],
      },
}
```

Let me know if you need any more assistance.

Nate

**Comment by challengy1** [comment]
Hi Nate,

Thank you so much for your swift reply. I confess that I didn't setup the css completely. After I made it sure, the image was successfully located on the left side. GOOD!

BR, KI

**Comment by newsproutsmedia** [comment]
You're very welcome! I'm glad I could help. Best of luck on your project.

Nate
